### PR TITLE
Kotlin library

### PR DESCRIPTION
**Pull request by AndresMx35**
Hi. 

I just pass your RecordButton library to Kotlin and add an example on your package. What do you think?

### CODE REVIEW

**Review by emrekose26 — CHANGES_REQUESTED** [review]
Thanks, @AndresMx35. But there are some things that should change. 

- You should `.gradle` and `.idea` folders. That folders are unnecessary. 
- Also, you should change the package name. Project package name is not the same as my package name that you have added parts. You must change `com.anadromo.kotlin_recordbutton_lib` to `com.emrekose.kotlin_recordbutton_lib`

**Comment by AndresMx35** [comment]
Ok, let me fix it.

**Comment by AndresMx35** [comment]
I think it's ok already based on your last review. Can you review it?

**Comment by emrekose26** [comment]
Thanks @AndresMx35

**Pull request merged**
