### PR TITLE
Rewrite to kotlin

### PR DESCRIPTION
**Pull request by alfianyusufabdullah**
Trying rewrite to kotlin & bump dependencies version #10

### CODE REVIEW

**Review by emrekose26 — CHANGES_REQUESTED** [review]
Thank you for your contribution 👍  
Could you remove `.gradle` and `.idea` folder? That folders are unnecessary.

**Comment by alfianyusufabdullah** [comment]
on next PR if this PR is merged

**Comment by emrekose26** [comment]
I'll be waiting for your next PR.

**Comment by alfianyusufabdullah** [comment]
working on it

**Comment by alfianyusufabdullah** [comment]
remove it #14

**Pull request merged**
